[profile.default]
# anything taking longer than a couple seconds is suspicious
slow-timeout = "1s"

[[profile.default.overrides]]
filter = 'test(timeout_*)'
# CSES only gives us 1 second, so timeout after three
slow-timeout = { period = "1s", terminate-after = 3 }
